services:
  database:
    container_name: printerQueDB
    image: mariadb:latest
    ports:
      - "3345:3306"
    environment:
      - MYSQL_DATABASE=printerque
      - MYSQL_PASSWORD=W7UDz^%Fj@lkwHi$
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=W7UDz^%Fj@lkwHi$
    restart: unless-stopped
    volumes:
      - printer-que-db:/var/lib/mysql
    networks:
      - printer-que

  printer_que:
    container_name: Printer_Que
    image: registry.kedi-server.de/printer-que:latest
    ports:
      - "8045:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - printer-que


volumes:
  printer-que-db:
  octoprint:

networks:
  printer-que: