services:
  database:
    container_name: printerQueDB
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=printerque
      - MYSQL_PASSWORD=Password1
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=Password1
    restart: unless-stopped
    volumes:
      - printer-que-db:/var/lib/mysql

volumes:
  printer-que-db: