_version: 2
onlyKeno:
  active: true
  apikey: F374B80D832F4D6F94DC9A5B9D669DE8
  groups:
  - users
  - admins
  password: $argon2id$v=19$m=65536,t=3,p=4$1lrrfS/FWIvR+t/7n3OOcQ$ZDbIap3Fk7khlvmYKDGtqEt/NaR1uHmHHDaj9YWldAg
  permissions: []
  roles:
  - user
  - admin
  settings: {}
